name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sudo apt install -y gcc-10 curl
    - name: get version
      run: g++ -v
    - name: compile
      run: make examples
